custombucket = "awsdevopscustom"
table = "intellipaat"
databasehost = "database-1-aws-devops-instance-1.czwkaqmi6kv6.us-east-1.rds.amazonaws.com"
duser = "awsdevops"
dpass = "awsdevops123"
s3database = "intellipaat"
kapp = "http://3.228.220.21/"
